# Generated by Django 3.0.1 on 2020-01-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyjob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cMobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cVacancyNumber',
            field=models.IntegerField(),
        ),
    ]
