# Generated by Django 3.0.1 on 2020-02-04 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyjob', '0002_auto_20200124_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Company',
        ),
    ]
