# Generated by Django 2.2.7 on 2020-02-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyjob', '0004_auto_20200208_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='CompanyName',
            new_name='cCompanyName',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Email',
            new_name='cEmail',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Location',
            new_name='cLocation',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Mobile',
            new_name='cMobile',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='VacancyNumber',
            new_name='cVacancyNumber',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='VacantPost',
            new_name='cVacantPost',
        ),
    ]
