# Generated by Django 3.0.1 on 2020-01-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_Name', models.CharField(max_length=20)),
                ('Applicant_Email', models.EmailField(max_length=30)),
                ('Applicant_Mobile_No', models.IntegerField()),
                ('Applicant_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=20)),
                ('Company_Email', models.EmailField(max_length=30)),
                ('Mobile_No', models.IntegerField()),
                ('Company_Location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education', models.TextField(max_length=40)),
                ('Experience', models.TextField(max_length=40)),
                ('Applicant_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model_Relationship.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vacent_post', models.CharField(max_length=100)),
                ('Vacency_no', models.IntegerField()),
                ('Applicant_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model_Relationship.Applicant')),
                ('CompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model_Relationship.Company')),
            ],
        ),
    ]
