# Generated by Django 3.0.1 on 2020-01-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Relationship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='Applicant_Name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='CompanyName',
        ),
    ]
