# Generated by Django 3.0.1 on 2020-02-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Relationship', '0002_auto_20200124_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='CompanyName',
            new_name='Employer',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='Applicant_Name',
            new_name='Employee',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Applicant_Name',
        ),
        migrations.AddField(
            model_name='applicant',
            name='Applicant_Name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='CompanyName',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='Jobseeker',
            field=models.ManyToManyField(blank=True, related_name='jobseeker', to='Model_Relationship.Applicant'),
        ),
    ]
