# Generated by Django 3.0.1 on 2020-02-04 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Relationship', '0003_auto_20200202_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('Applicant_Profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Model_Relationship.Applicant')),
            ],
        ),
    ]
